import { User, DonVi, Personnel, TS_Xe, CP_HoatDongXe, PhapNhan, PhongHop, VB_TB, ThietBi, NhatKyThietBi, ATVSLD, HS_PCCC, TS_PCCC, PCTT } from '../../types';

export const INITIAL_MOCK_DATA: Record<string, any[]> = {
  config_users: [
    {
      id: 'USR1',
      user_name: 'admin',
      password: '1',
      ho_ten: 'Quản trị viên Hệ thống',
      id_don_vi: 'ALL',
      quyen: 'admin',
      quyen_truy_cap: '',
      quyen_chi_tiet: ''
    },
    {
      id: 'USR2',
      user_name: 'user',
      password: '1',
      ho_ten: 'Nguyễn Lương Minh Thiện',
      id_don_vi: 'SR1',
      quyen: 'user',
      quyen_truy_cap: 'TongQuan,Xe',
      quyen_chi_tiet: ''
    }
  ],

  dm_don_vi: [
    {
      id: 'HO',
      ten_don_vi: 'Văn phòng Điều hành (HO)',
      cap_quan_ly: '',
      dia_chi: 'TP. Hồ Chí Minh',
      dien_tich: 1200,
      so_tang: 5,
      so_ham: 1,
      so_phong_cho: 3,
      so_cong: 1,
      luot_khach_bq: 150,
      tong_nhan_su: 85,
      loai_hinh: 'Văn phòng',
      trang_thai: 'Hoạt động',
      phia: 'Nam'
    },
    {
      id: 'SR1',
      ten_don_vi: 'Showroom Bình Dương',
      cap_quan_ly: 'HO',
      dia_chi: 'Đại lộ Bình Dương, Thủ Dầu Một',
      dien_tich: 800,
      so_tang: 2,
      so_ham: 0,
      so_phong_cho: 2,
      so_cong: 2,
      luot_khach_bq: 80,
      tong_nhan_su: 32,
      loai_hinh: 'Showroom',
      trang_thai: 'Hoạt động',
      phia: 'Nam'
    },
    {
      id: 'SR2',
      ten_don_vi: 'Showroom Hà Nội',
      cap_quan_ly: 'HO',
      dia_chi: 'Cầu Giấy, Hà Nội',
      dien_tich: 1000,
      so_tang: 3,
      so_ham: 1,
      so_phong_cho: 4,
      so_cong: 2,
      luot_khach_bq: 120,
      tong_nhan_su: 40,
      loai_hinh: 'Showroom',
      trang_thai: 'Hoạt động',
      phia: 'Bắc'
    }
  ],

  ns_dich_vu: [
    {
      id: 'NS1',
      ma_so_nhan_vien: '2112277',
      ho_ten: 'Nguyễn Lương Minh Thiện',
      chuc_vu: 'Trưởng bộ phận Hành chính',
      sdt_cong_ty: '0901234567',
      sdt_ca_nhan: '0987654321',
      email: 'thien.nlm@company.com',
      gioi_tinh: 'Nam',
      nam_sinh: '1995',
      ngay_nhan_viec: '2021-12-01',
      id_don_vi: 'SR1',
      chuc_danh: 'Văn phòng',
      trinh_do_hoc_van: 'Đại học',
      thu_nhap: 22000000,
      mo_ta_ngoai_hinh: 'Cao 1m75, đeo kính',
      ghi_chu: 'Phụ trách chung văn phòng Bình Dương',
      cc_atvsld: true,
      cc_anbv: false,
      cc_pccc: true,
      cc_cnch: false,
      cc_so_cap_cuu: true,
      cc_cpr: true,
      cc_vo_thuat: false,
      giay_phep_lai_xe: 'B2',
      cc_attp: false,
      cc_pha_che: false,
      cc_ngoai_ngu: true,
      cc_tin_hoc: true,
      trang_thai: 'Đang làm việc',
      ngay_nghi_viec: ''
    },
    {
      id: 'NS2',
      ma_so_nhan_vien: '2201002',
      ho_ten: 'Nguyễn Đức Hồng Long',
      chuc_vu: 'Nhân viên Bảo vệ',
      sdt_cong_ty: '0902345678',
      sdt_ca_nhan: '0976543210',
      email: 'long.ndh@company.com',
      gioi_tinh: 'Nam',
      nam_sinh: '1998',
      ngay_nhan_viec: '2022-01-15',
      id_don_vi: 'SR1',
      chuc_danh: 'Bảo vệ',
      trinh_do_hoc_van: 'Trung học',
      thu_nhap: 9500000,
      mo_ta_ngoai_hinh: 'Cao 1m80, khỏe mạnh',
      ghi_chu: 'Làm ca đêm',
      cc_atvsld: true,
      cc_anbv: true,
      cc_pccc: true,
      cc_cnch: true,
      cc_so_cap_cuu: true,
      cc_cpr: false,
      cc_vo_thuat: true,
      giay_phep_lai_xe: 'A1',
      cc_attp: false,
      cc_pha_che: false,
      cc_ngoai_ngu: false,
      cc_tin_hoc: false,
      trang_thai: 'Đang làm việc',
      ngay_nghi_viec: ''
    }
  ],

  ts_xe: [
    {
      id: 'XE1',
      id_don_vi: 'SR1',
      muc_dich_su_dung: 'Giao xe khách hàng',
      ma_tai_san: 'TS-XE-001',
      don_vi_so_huu: 'Chi nhánh Bình Dương',
      nguyen_gia: 950000000,
      khau_hao_thue: 10000000,
      bien_so: '61A-123.45',
      loai_phuong_tien: 'Ô tô con',
      hieu_xe: 'Toyota',
      loai_xe: 'Camry',
      phien_ban: '2.5Q',
      mau_xe: 'Đen',
      nam_sx: 2022,
      nam_dk: 2022,
      so_khung: 'RLAA1234567890',
      so_may: '2AR-FE123456',
      so_cho: 5,
      loai_nhien_lieu: 'Xăng',
      dung_tich: '2.5L',
      cong_thuc_banh: '4x2',
      hinh_thuc_so_huu: 'Mua mới',
      gps: 'Có',
      hien_trang: 'Hoạt động',
      ghi_chu: 'Xe đi giao showroom thường xuyên'
    },
    {
      id: 'XE2',
      id_don_vi: 'SR1',
      muc_dich_su_dung: 'Xe lái thử',
      ma_tai_san: 'TS-XE-002',
      don_vi_so_huu: 'Chi nhánh Bình Dương',
      nguyen_gia: 850000000,
      khau_hao_thue: 8000000,
      bien_so: '61A-678.90',
      loai_phuong_tien: 'Ô tô con',
      hieu_xe: 'Kia',
      loai_xe: 'Seltos',
      phien_ban: '1.4 Premium',
      mau_xe: 'Trắng',
      nam_sx: 2023,
      nam_dk: 2023,
      so_khung: 'RLAB1234567890',
      so_may: 'K3F-FE123456',
      so_cho: 5,
      loai_nhien_lieu: 'Xăng',
      dung_tich: '1.4L',
      cong_thuc_banh: '4x2',
      hinh_thuc_so_huu: 'Sở hữu',
      gps: 'Có',
      hien_trang: 'Hoạt động',
      ghi_chu: 'Xe lái thử cho khách hàng'
    },
    {
      id: 'XE3',
      id_don_vi: 'SR1',
      muc_dich_su_dung: 'Xe công',
      ma_tai_san: 'TS-XE-003',
      don_vi_so_huu: 'Chi nhánh Bình Dương',
      nguyen_gia: 1200000000,
      khau_hao_thue: 12000000,
      bien_so: '61A-555.55',
      loai_phuong_tien: 'Ô tô con',
      hieu_xe: 'Mazda',
      loai_xe: 'CX-8',
      phien_ban: 'Premium',
      mau_xe: 'Đỏ',
      nam_sx: 2022,
      nam_dk: 2022,
      so_khung: 'RLAC1234567890',
      so_may: 'PY-VPS123456',
      so_cho: 7,
      loai_nhien_lieu: 'Xăng',
      dung_tich: '2.5L',
      cong_thuc_banh: '4x2',
      hinh_thuc_so_huu: 'Sở hữu',
      gps: 'Có',
      hien_trang: 'Hoạt động',
      ghi_chu: 'Xe đưa đón ban giám đốc showroom'
    },
    {
      id: 'XE4',
      id_don_vi: 'SR2',
      muc_dich_su_dung: 'Xe công',
      ma_tai_san: 'TS-XE-004',
      don_vi_so_huu: 'Chi nhánh Hà Nội',
      nguyen_gia: 1500000000,
      khau_hao_thue: 15000000,
      bien_so: '29A-999.99',
      loai_phuong_tien: 'Ô tô con',
      hieu_xe: 'BMW',
      loai_xe: '320i',
      phien_ban: 'Sport Line',
      mau_xe: 'Xanh',
      nam_sx: 2021,
      nam_dk: 2021,
      so_khung: 'RLAD1234567890',
      so_may: 'B48B20A123456',
      so_cho: 5,
      loai_nhien_lieu: 'Xăng',
      dung_tich: '2.0L',
      cong_thuc_banh: '4x2',
      hinh_thuc_so_huu: 'Sở hữu',
      gps: 'Có',
      hien_trang: 'Hoạt động',
      ghi_chu: 'Xe công tác Hà Nội'
    }
  ],

  cp_hoat_dong_xe: [
    {
      id: 'CP1',
      id_don_vi: 'SR1',
      thang_nam: '2026-06',
      id_ts_xe: 'XE1',
      km_hien_tai: 18500,
      so_lit_nhien_lieu: 140,
      cp_nhien_lieu: 3200000,
      cp_cau_duong_ben_bai: 450000,
      cp_rua_xe: 180000,
      cp_bao_duong_sua_chua: 1200000,
      cp_thue_khau_hao: 0,
      ghi_chu: 'Đi công tác tỉnh nhiều'
    }
  ],

  ts_thiet_bi: [
    {
      id: 'TB1',
      id_don_vi: 'SR1',
      ma_tai_san: 'TS-IT-001',
      ten_thiet_bi: 'PC Gaming Văn Phòng',
      nhom_thiet_bi: 'Máy móc CNTT (PC, Laptop, Server...)',
      mo_ta_dac_diem: 'Core i7, RAM 16GB, SSD 512GB',
      nha_cung_cap: 'Phong Vũ IT',
      ngay_mua: '2023-05-10',
      gia_mua: '18500000',
      han_bao_hanh: '2025-05-10',
      tinh_trang: 'Tốt',
      link_hinh_anh: '',
      link_ho_so: '',
      so_seri: 'PCDELL12345',
      cpu: 'Core i7 12700',
      ram: '16GB',
      ssd: '512GB',
      hdd: 'None',
      vga: 'GTX 1650',
      man_hinh: 'Dell 24 inch',
      phu_kien: 'Chuột, phím, tai nghe',
      don_vi_tinh: 'Bộ',
      quy_cach_chat_lieu: 'Kim loại/Nhựa',
      thoi_gian_khau_hao: '3 năm',
      tai_san_thuoc: 'Công ty sở hữu'
    }
  ],

  nk_thiet_bi: [
    {
      id: 'NK1',
      id_ts_thiet_bi: 'TB1',
      id_don_vi: 'SR1',
      ngay_ghi_nhan: '2023-05-11',
      loai_nhat_ky: 'Bàn giao',
      msnv_nguoi_dung: '2112277',
      ho_ten_nguoi_dung: 'Nguyễn Lương Minh Thiện',
      bp_quan_ly_su_dung: 'Bộ phận Hành chính',
      ghi_chu_sua_chua_nang_cap: 'Bàn giao máy mới 100%',
      tinh_trang_ghi_nhan_thiet_bi: 'Mới nguyên seal',
      chi_phi: 0
    }
  ],

  hs_an_ninh: [
    {
      id: 'AN1',
      id_don_vi: 'SR1',
      bv_noi_bo: 2,
      bv_dich_vu: 4,
      vi_tri_bv_dv: 'Cổng chính và Bãi xe',
      ncc_dich_vu: 'Công ty Bảo vệ Thắng Lợi',
      chi_phi_thue: 35000000,
      tong_bv: 6,
      dinh_bien_bv: 6,
      ngay_co_dinh: 1,
      ngay_tuan_tra: 1,
      dem_co_dinh: 1,
      dem_tuan_tra: 1,
      bo_tri_nghi: 'Xoay ca tuần',
      sl_camera: 16,
      thoi_gian_luu: '30 ngày',
      vi_tri_giam_sat: 'Phòng bảo vệ trung tâm',
      tinh_hinh_khu_vuc: 'An ninh tốt',
      tiep_giap_truoc: 'Đường quốc lộ',
      tiep_giap_sau: 'Khu dân cư',
      tiep_giap_trai: 'Công ty xăng dầu',
      tiep_giap_phai: 'Đất trống',
      link_pa_anbv: '',
      camera_hoat_dong: 15,
      camera_hu: 1,
      ly_do_camera_hu: 'Hỏng nguồn ngoài trời',
      vi_tri_he_thong_camera: 'Mái hiên showroom',
      vi_tri_gs_camera: 'Phòng bảo vệ'
    }
  ],

  hs_pvhc: [],
  hs_pctt: [],
  sys_logs: [],

  hs_pccc: [
    {
      id: 'PCCC1',
      id_don_vi: 'SR1',
      giay_phep_pccc: 'GP-PCCC-BD2022',
      bao_hiem_chay_no: 'BHCN-123456',
      ngay_het_han_bh: '2026-12-31',
      ho_ten_doi_truong: 'Nguyễn Lương Minh Thiện',
      sdt_doi_truong: '0901234567',
      chuc_vu: 'Đội trưởng PCCC cơ sở',
      tong_sl_thanh_vien: 10,
      sl_huy_dong_ban_ngay: 6,
      sl_huy_dong_ban_dem: 4,
      ngay_dien_tap: '2025-10-15',
      sdt_ca_pccc: '114',
      ten_ca_pccc: 'Phòng Cảnh sát PCCC và CNCH',
      sdt_ub: '0274-123456',
      ten_ub: 'UBND Phường Thốt Nốt',
      sdt_pccc_xa_phuong: '0333747488',
      ten_pccc_xa_phuong: 'Phòng Cảnh sát PCCC và CNCH',
      sdt_ca_xa_phuong: '0274-888888',
      ten_ca_xa_phuong: 'Công an Phường Thốt Nốt',
      sdt_dien_luc: '19001247',
      ten_dien_luc: 'Đơn vị điện lực Thốt Nốt',
      sdt_cap_thoat_nuoc: '0274-555555',
      ten_cap_thoat_nuoc: 'Công ty Cấp thoát nước',
      sdt_yte: '02923 854 939',
      ten_yte: 'Bệnh viện Thốt Nốt',
      sdt_bv_dan_quan: '02923 644 725',
      ten_bv_dan_quan: 'Công an phường Thốt Nốt',
      sdt_ca_khu_vuc: '02923 644 725',
      ten_ca_khu_vuc: 'Công an phường Thốt Nốt',
      sdt_kho_xe: '0938.808.194',
      ten_kho_xe: 'Nguyễn Tấn Tài',
      sdt_tt_bao_ve: '0902.111.846',
      ten_tt_bao_ve: 'Nguyễn Thanh Tân',
      sdt_hc_ns: '0938.907.811',
      ten_hc_ns: 'Nguyễn Thị Thảo',
      sdt_bv_lien_ket: '02923 854 939',
      ten_bv_lien_ket: 'Bệnh viện Thốt Nốt',
      ht_bao_chay_tu_dong: 'Hoạt động tốt',
      ht_chua_chay_tu_dong_nuoc: 'Không có',
      ht_chua_chay_nuoc: 'Họng nước vách tường hoạt động tốt',
      dung_cu_pccc: 'Bình chữa cháy xách tay, rìu, búa, câu liêm',
      khu_vuc_rui_ro_cao: 'Kho phụ tùng, Bãi chứa xe',
      loi_ton_tai_chua_khac_phuc: 'Thiếu 2 biển chỉ dẫn exit ở tầng lửng',
      ghi_chu: 'Kế hoạch kiểm tra định kỳ hàng tháng'
    }
  ],

  ts_pccc: [
    {
      id: 'TSPCCC1',
      id_don_vi: 'SR1',
      nhom_he_thong: 'Bình chữa cháy xách tay',
      loai_thiet_bi: 'Bình bột BC MFZ4',
      so_luong: 24,
      don_vi_tinh: 'Bình',
      vi_tri_bo_tri: 'Dọc hành lang và khu vực kỹ thuật',
      ngay_bom_sac: '2025-11-20',
      ngay_het_han: '2026-11-20',
      tinh_trang: 'Đầy áp suất, sẵn sàng dùng'
    }
  ],

  hs_an_toan_lao_dong: [
    {
      id: 'ATLD1',
      id_don_vi: 'SR1',
      nguoi_phu_trach: 'Nguyễn Lương Minh Thiện',
      so_luong_mang_luoi: 3,
      link_ho_so_quy_dinh: '',
      khoa_huan_luyen_tu: '2025-03-01',
      khoa_huan_luyen_den: '2025-03-03',
      can_cu_quyet_dinh: 'QĐ-HL-ATLD-SR1',
      thong_ke_hl: { total: 32, passed: 32, failed: 0 },
      ty_le_hoan_thanh_hl: '100%',
      ngay_ksk: '2025-06-15',
      ngay_kham_bnn: '2025-06-16',
      so_luong_thiet_bi_nghiem_ngat: 2,
      so_luong_thiet_bi_qua_han_kt: 0,
      ngay_quan_trac_mt: '2025-09-10',
      ty_le_cap_bhld: '100%',
      ngay_tu_kiem_tra: '2026-05-15',
      cac_loi_hien_truong: 'Không phát hiện lỗi nghiêm trọng',
      so_tai_nan_trong_nam: 0,
      link_bien_ban_kiem_tra: '',
      ghi_chu: 'Duy trì vệ sinh 5S hàng ngày'
    }
  ],

  dm_phap_nhan: [
    {
      id: 'PN1',
      id_don_vi: 'HO',
      ten_cong_ty: 'CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ Ô TÔ',
      ma_so_thue: '0312345678',
      dia_chi: 'Quận 1, TP. Hồ Chí Minh',
      gpkd: 'ĐKKD số 0312345678 do Sở KHĐT TP.HCM cấp',
      mail: 'contact@company.com'
    }
  ],

  dm_phong_hop: [
    {
      id: 'PH1',
      id_don_vi: 'HO',
      ten_phong_hop: 'Phòng họp Hội đồng (VIP)',
      vi_tri: 'Tầng 4, tòa nhà HO',
      suc_chua: '30 người',
      tb_trinh_chieu: 'Màn hình LED 100 inch',
      tb_hop_online: true,
      bang_viet: true,
      but_viet: 'Có sẵn',
      but_chi: 'Có sẵn',
      tb_chuyen_slide: true,
      layout: 'Oval',
      ghi_chu: 'Yêu cầu đăng ký trước 24 tiếng'
    }
  ],

  qd_qt: [
    {
      id: 'QD1',
      id_don_vi: 'HO',
      phan_loai: 'Quy định',
      so_hieu: 'QD-01-2025',
      ngay_ban_hanh: '2025-01-01',
      tieu_de: 'Quy định Sử dụng Tài sản và Thiết bị Công nghệ',
      noi_dung: 'Tất cả cán bộ nhân viên phải bảo quản trang thiết bị làm việc được giao...',
      nguoi_ky: 'Tổng Giám Đốc',
      hieu_luc: 'Có hiệu lực',
      nghiep_vu: 'Quản trị Văn phòng',
      link_vb: '',
      vb_thay_the: '',
      mat: false
    }
  ],

  vb_tb: [
    {
      id: 'VB1',
      id_don_vi: 'HO',
      phan_loai: 'Văn bản đến',
      so_hieu: 'VB-128-SXD',
      ngay_ban_hanh: '2026-05-12',
      tieu_de: 'Về việc kiểm tra phòng chống lụt bão mùa mưa năm 2026',
      noi_dung: 'Công văn từ Sở Xây dựng yêu cầu các doanh nghiệp rà soát hạ tầng phòng chống thiên tai...',
      nguoi_ky: 'Phó Giám đốc Sở',
      chuc_vu: 'Phó Giám đốc',
      nguoi_lay_so: 'Văn thư HO',
      bo_phan_lay_so: 'Hành chính Tổng hợp',
      pham_vi_ap_dung: 'Toàn hệ thống',
      hieu_luc: 'Có hiệu lực',
      nghiep_vu: 'Văn thư lưu trữ',
      link_vb: '',
      vb_thay_the: '',
      mat: false,
      so_den: 'SXD-1025',
      ngay_nhan: '2026-05-14',
      bo_phan_xu_ly: 'Ban Quản lý cơ sở vật chất',
      han_xu_ly: '2026-06-15',
      trang_thai_xu_ly: 'Đang xử lý',
      muc_do_khan: 'Khẩn'
    }
  ],

  dm_ncc: [
    {
      id: 'NCC1',
      ten_cong_ty: 'Công ty Cổ phần Nước khoáng Lavie',
      ten_goi_tat: 'Lavie',
      mst: '0100112233',
      dai_dien_phap_luat: 'Giulio Alberoni',
      chuc_vu_ddpl: 'Giám đốc',
      sdt_ddpl: '02839401234',
      dau_moi: 'Nguyễn Văn Nam',
      chuc_vu_dau_moi: 'Trưởng phòng Hành chính',
      sdt_dau_moi: '0909123456',
      email_dau_moi: 'nam.nguyen@laviewater.com',
      dia_chi: 'Khánh Hậu, Tân An, Long An',
      nhom_dich_vu: 'Nước uống',
      dich_vu: 'Cung cấp nước khoáng bình 19L và chai nhỏ',
      id_don_vi: 'HO',
      ngay_bat_dau_hd: '2025-01-01',
      ngay_het_han_hd: '2026-12-31',
      danh_gia: 'Dịch vụ giao hàng nhanh, nước chất lượng tốt',
      trang_thai: 'Đang hợp tác',
      hinh_thuc_tt: 'Chuyển khoản chậm 30 ngày',
      link_ho_so: 'https://laviewater.com',
      ghi_chu: 'Cấp vỏ bình đặt cọc 50.000đ/vỏ',
      dau_moi_json: [],
      gia_han_tu_dong: 12
    }
  ],

  nk_su_dung_xe: [
    {
      id: 'NKSD1',
      id_don_vi: 'SR1',
      bien_so: '61A-12345',
      nguoi_de_xuat: 'Nguyễn Lương Minh Thiện',
      lai_xe: 'Trần Văn Tài',
      muc_dich_su_dung: 'Sửa chữa lưu động',
      thoi_gian_su_dung: '08:30 - 17:30, Ngày 15/08/2026',
      noi_di: 'Showroom Bình Dương',
      noi_den: 'Khách hàng Thuận An',
      so_km_di: 18500,
      so_km_ve: 18545,
      tong_km: 45,
      file_name: 'Phieu_De_Xuat_61A12345.pdf',
      created_at: '2026-08-15T08:30:00Z'
    }
  ],

  dm_bo_phan_cap1: [
    { id: 'BP1_QTC', ma: 'QTC', ten: 'Nghiệp vụ QTC', yeu_cau_cap2: false, thu_tu: 1, active: true },
    { id: 'BP1_KD',  ma: 'KD',  ten: 'Kinh doanh',    yeu_cau_cap2: true,  thu_tu: 2, active: true },
    { id: 'BP1_DV',  ma: 'DV',  ten: 'Dịch vụ',       yeu_cau_cap2: true,  thu_tu: 3, active: true },
    { id: 'BP1_XSC', ma: 'XSC', ten: 'Xưởng Sửa chữa',yeu_cau_cap2: true,  thu_tu: 4, active: true },
    { id: 'BP1_DC',  ma: 'DC',  ten: 'Dùng chung & Khác', yeu_cau_cap2: false, thu_tu: 5, active: true }
  ],

  dm_bo_phan_cap2: [
    { id: 'BP2_KIA',     ma: 'KIA',     ten: 'Kia',          thu_tu: 1, active: true },
    { id: 'BP2_MAZDA',   ma: 'MAZDA',   ten: 'Mazda',        thu_tu: 2, active: true },
    { id: 'BP2_PEUGEOT', ma: 'PEUGEOT', ten: 'Peugeot',      thu_tu: 3, active: true },
    { id: 'BP2_BMW',     ma: 'BMW',     ten: 'BMW',          thu_tu: 4, active: true },
    { id: 'BP2_TAIBUS',  ma: 'TAIBUS',  ten: 'Tải bus',      thu_tu: 5, active: true },
    { id: 'BP2_MOTORRAD',ma: 'MOTORRAD',ten: 'BMW Motorrad', thu_tu: 6, active: true },
    { id: 'BP2_RAM',     ma: 'RAM',     ten: 'RAM',          thu_tu: 7, active: true },
    { id: 'BP2_JEEP',    ma: 'JEEP',    ten: 'JEEP',         thu_tu: 8, active: true }
  ],

  dm_kmp: [
    { id: 'KMP1', ma_b7: 'B7.01', ma_b10: 'B10.01', nhom_chi_phi: 'Chi phí Năng lượng', dien_giai: 'Tiền điện Tổ hợp Showroom', trong_yeu: true, active: true },
    { id: 'KMP2', ma_b7: 'B7.02', ma_b10: 'B10.02', nhom_chi_phi: 'Chi phí Năng lượng', dien_giai: 'Tiền nước sinh hoạt', trong_yeu: false, active: true },
    { id: 'KMP3', ma_b7: 'B7.03', ma_b10: 'B10.03', nhom_chi_phi: 'Chi phí Dịch vụ ngoài', dien_giai: 'Dịch vụ vệ sinh công nghiệp', trong_yeu: true, active: true },
    { id: 'KMP4', ma_b7: 'B7.04', ma_b10: 'B10.04', nhom_chi_phi: 'Chi phí Dịch vụ ngoài', dien_giai: 'Dịch vụ an ninh trật tự - bảo vệ', trong_yeu: true, active: true },
    { id: 'KMP5', ma_b7: 'B7.05', ma_b10: 'B10.05', nhom_chi_phi: 'Chi phí Văn phòng phẩm', dien_giai: 'Giấy in, mực in, đồ dùng văn phòng', trong_yeu: false, active: true }
  ],

  dntt: [
    {
      id: 'DNTT1',
      so_dntt: 'DNTT-2026-0001',
      ngay_lap: '2026-08-20',
      id_phap_nhan: 'PN1',
      id_don_vi: 'SR1',
      nguoi_de_nghi: 'Hồ Khánh Băng',
      bo_phan_hien_thi: 'QTPV, AS & MTLV',
      noi_dung_thanh_toan: 'Tiền điện tháng 08 năm 2026',
      tong_so_tien: 76379844,
      so_tien_bang_chu: 'Bảy mươi sáu triệu ba trăm bảy mươi chín nghìn tám trăm bốn mươi bốn đồng',
      hinh_thuc_thanh_toan: 'Chuyển khoản',
      ten_tai_khoan: 'CÔNG TY ĐIỆN LỰC ĐỒNG THÁP',
      so_tai_khoan: '1234567890123',
      ten_ngan_hang: 'Vietcombank',
      chi_nhanh_ngan_hang: 'Chi nhánh Đồng Tháp',
      trang_thai: 'Đã duyệt'
    }
  ],

  dntt_chi_tiet: [
    {
      id: 'CT1',
      dntt_id: 'DNTT1',
      stt: 1,
      noi_dung: 'Tiền điện Tổ hợp Showroom MKH: PB08080121471',
      so_tien: 76379844
    }
  ],

  dntt_phan_bo: [
    { id: 'PB1',  dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 5346589, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_QTC', id_bo_phan_cap2: undefined, thu_tu: 1 },
    { id: 'PB2',  dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 6110388, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_KD',  id_bo_phan_cap2: 'BP2_KIA', thu_tu: 2 },
    { id: 'PB3',  dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 6110388, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_KD',  id_bo_phan_cap2: 'BP2_MAZDA', thu_tu: 3 },
    { id: 'PB4',  dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 6110388, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_KD',  id_bo_phan_cap2: 'BP2_PEUGEOT', thu_tu: 4 },
    { id: 'PB5',  dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 6110388, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_KD',  id_bo_phan_cap2: 'BP2_BMW', thu_tu: 5 },
    { id: 'PB6',  dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 3818992, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_DV',  id_bo_phan_cap2: 'BP2_KIA', thu_tu: 6 },
    { id: 'PB7',  dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 3818992, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_DV',  id_bo_phan_cap2: 'BP2_MAZDA', thu_tu: 7 },
    { id: 'PB8',  dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 1527597, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_DV',  id_bo_phan_cap2: 'BP2_PEUGEOT', thu_tu: 8 },
    { id: 'PB9',  dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 1527597, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_DV',  id_bo_phan_cap2: 'BP2_BMW', thu_tu: 9 },
    { id: 'PB10', dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 6874186, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_XSC', id_bo_phan_cap2: 'BP2_KIA', thu_tu: 10 },
    { id: 'PB11', dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 6874186, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_XSC', id_bo_phan_cap2: 'BP2_MAZDA', thu_tu: 11 },
    { id: 'PB12', dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 3818992, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_XSC', id_bo_phan_cap2: 'BP2_PEUGEOT', thu_tu: 12 },
    { id: 'PB13', dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 3818992, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_XSC', id_bo_phan_cap2: 'BP2_BMW', thu_tu: 13 },
    { id: 'PB14', dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 3055194, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_KD',  id_bo_phan_cap2: 'BP2_TAIBUS', thu_tu: 14 },
    { id: 'PB15', dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 3818992, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_DV',  id_bo_phan_cap2: 'BP2_TAIBUS', thu_tu: 15 },
    { id: 'PB16', dntt_id: 'DNTT1', dntt_chi_tiet_id: 'CT1', kieu_nhap: 'SO_TIEN', so_tien: 7637984, id_kmp: 'KMP1', thang: 8, nam: 2026, id_bo_phan_cap1: 'BP1_XSC', id_bo_phan_cap2: 'BP2_TAIBUS', thu_tu: 16 }
  ]
};
